### ISSUE TITLE
RE-RENDERING recentbooks.tsx so i cant click or run any logic into its child components

### ISSUE THREAD

**Issue by anwar-2000** [anwar-2000/bookstore#1]

**Comment by modecode22** [comment]
can you provide more details  ?

**Comment by anwar-2000** [comment]
Yes , the bookItem component has a click trigger functionalities and if I pass false to "show buttons" then the buttons are hidden , none of this work that's the problem

**Comment by abdeldjalilhachimi** [comment]
Would you like to show as your code, let's see how can we help you in this issue

**Comment by anwar-2000** [comment]
> @abdeldjalilhachimi 

Check the RecentBooks.tsx in index.tsx , half of it start working thanks to @modecode22 and now the logic of buttons isn't working when changing the props of "showbuttons" to true
